import { EligibilityRepository } from '../repositories/eligibility.repository';
import { StoreEvaluationResultSchema } from '../schemas/eligibility.schema';
import { AppError } from '../../../shared/errors/AppError';

export class EligibilityService {
  constructor(private readonly repository: EligibilityRepository) {}

  async listEvaluations(filters?: { familyId?: string; schemeId?: string; status?: string }) {
    return this.repository.listEvaluations(filters);
  }

  async getEvaluation(id: string) {
    return this.repository.getEvaluationById(id);
  }

  async getEvaluationsForFamily(familyId: string) {
    return this.repository.getEvaluationsForFamily(familyId);
  }

  /**
   * Deterministic rule engine: evaluates a family/member against a scheme version's rules.
   */
  async evaluateEligibility(familyData: any, memberData: any, schemeVersion: any) {
    const rules = schemeVersion.rule_definition || {};
    const ruleGroups = rules.groups || [];
    
    const results: { rule: string; group: string; status: 'PASSED' | 'FAILED' | 'MISSING_INFO'; detail: string }[] = [];
    const missingInfo: string[] = [];
    let overallStatus: 'ELIGIBLE' | 'NOT_ELIGIBLE' | 'NEEDS_INFORMATION' = 'ELIGIBLE';

    for (const group of ruleGroups) {
      for (const rule of (group.rules || [])) {
        const evalResult = this.evaluateRule(rule, familyData, memberData);
        results.push({ rule: rule.name || rule.field, group: group.name, status: evalResult.status, detail: evalResult.detail });
        
        if (evalResult.status === 'FAILED') overallStatus = 'NOT_ELIGIBLE';
        if (evalResult.status === 'MISSING_INFO') {
          missingInfo.push(rule.name || rule.field);
          if (overallStatus !== 'NOT_ELIGIBLE') overallStatus = 'NEEDS_INFORMATION';
        }
      }
    }

    return {
      status: overallStatus,
      reasons: results,
      missing_information: missingInfo,
      evaluated_at: new Date().toISOString(),
    };
  }

  private evaluateRule(rule: any, familyData: any, memberData: any): { status: 'PASSED' | 'FAILED' | 'MISSING_INFO'; detail: string } {
    const target = memberData || familyData;
    const value = target?.[rule.field];

    if (value === undefined || value === null) {
      return { status: 'MISSING_INFO', detail: `Field '${rule.field}' is not provided.` };
    }

    switch (rule.operator) {
      case 'lte': return Number(value) <= Number(rule.value) 
        ? { status: 'PASSED', detail: `${rule.field} (${value}) ≤ ${rule.value}` }
        : { status: 'FAILED', detail: `${rule.field} (${value}) exceeds ${rule.value}` };
      case 'gte': return Number(value) >= Number(rule.value)
        ? { status: 'PASSED', detail: `${rule.field} (${value}) ≥ ${rule.value}` }
        : { status: 'FAILED', detail: `${rule.field} (${value}) below ${rule.value}` };
      case 'eq': return String(value) === String(rule.value)
        ? { status: 'PASSED', detail: `${rule.field} matches ${rule.value}` }
        : { status: 'FAILED', detail: `${rule.field} (${value}) ≠ ${rule.value}` };
      case 'in': return (rule.value as string[]).includes(String(value))
        ? { status: 'PASSED', detail: `${rule.field} (${value}) in [${rule.value}]` }
        : { status: 'FAILED', detail: `${rule.field} (${value}) not in [${rule.value}]` };
      case 'boolean': return Boolean(value) === Boolean(rule.value)
        ? { status: 'PASSED', detail: `${rule.field} is ${rule.value}` }
        : { status: 'FAILED', detail: `${rule.field} is ${value}, expected ${rule.value}` };
      default:
        return { status: 'MISSING_INFO', detail: `Unknown operator: ${rule.operator}` };
    }
  }

  /**
   * Persists an evaluation result generated by the deterministic rule engine.
   */
  async storeEvaluationResult(data: any) {
    const parsedData = StoreEvaluationResultSchema.parse(data);

    const evaluation = await this.repository.storeEvaluationResult({
      family_id: parsedData.familyId,
      member_id: parsedData.memberId || null,
      scheme_id: parsedData.schemeId,
      scheme_version_id: parsedData.schemeVersionId,
      status: parsedData.status,
      reasons: parsedData.reasons,
      missing_information: parsedData.missingInformation,
      evaluated_at: new Date().toISOString()
    });

    return evaluation;
  }
}
