import { EligibilityRepository } from '../repositories/eligibility.repository';
import { StoreEvaluationResultSchema } from '../schemas/eligibility.schema';

export class EligibilityService {
  constructor(private readonly repository: EligibilityRepository) {}

  /**
   * Persists an evaluation result generated by the deterministic rule engine.
   * Provides explainability for the frontend.
   */
  async storeEvaluationResult(data: any) {
    const parsedData = StoreEvaluationResultSchema.parse(data);

    const evaluation = await this.repository.storeEvaluationResult({
      family_id: parsedData.familyId,
      member_id: parsedData.memberId || null,
      scheme_id: parsedData.schemeId,
      scheme_version_id: parsedData.schemeVersionId,
      status: parsedData.status,
      reasons: parsedData.reasons,
      missing_information: parsedData.missingInformation,
      evaluated_at: new Date().toISOString()
    });

    return evaluation;
  }
}
